### ISSUE TITLE
Getting the below error in line 59

### ISSUE THREAD

**Issue by nyt1972** [Yizack/instagram-feed#1]
post() in C:\xampp\htdocs\insta\index.php:59 Stack trace: #0 {main} thrown in C:\xampp\htdocs\insta\index.php on line 59

the line 59 is: <?= post($username, $permalink, $caption, $timestamp); ?>

**Comment by Yizack** [comment]
I'm closing old issues, if help is still needed please open a new issue and provide a reproduction ✌🏼
