### ISSUE TITLE
For those who are interested in whether the module is working

### ISSUE THREAD

**Issue by dyakovlab** [Yizack/instagram-feed#6]
Checked on July 20, 2024 - everything is working correctly.
Also, if you need additional fields from the posts besides the default ones, simply pass the strings with their names when calling the `getFeed` method, for example, like this: `foreach($feed->getFeed('username,permalink,timestamp,caption,media_url') as $k => $value)`

The list of all available fields can be found [here](https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields).

**Comment by Yizack** [comment]
Thank you for reporting others and for the available fields link!
